name: hastor
version: 0.0.1
license: BSD3

dependencies:
  - base >= 4.19 && < 5
  - aeson # for JSON
  - split
  - utf8-string
  - http-conduit
  - network-simple # establish a simple TCP network
  - bytestring # useful to send bytes over the network
  - network # required when using bytestring
  - text # use Text rather than String
  - containers # may help with the database structure and debugging
  - time # may help with the expiry function
  - async # may help with concurrency
  - mtl # may help with structuring
  - binary # bytes for hashing
  - cryptonite # hashing 
  - SHA
  - base64
  - cryptohash-sha1 # SHA1
  - base16-bytestring
  - uri-encode
  # Parsing libs
  - megaparsec
  - parser-combinators
  - parsec
  - attoparsec

executables:
  hastor-exe:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hastor

tests:
  hastor-test:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hastor # Package library name
      - hspec # Testing framework
      - hspec-expectations # For Hspec-style expectations
    #- QuickCheck # For property-based testing (optional)
    ghc-options:
      - -threaded
      - -rtsopts
    #rts-options:
     # - "-N"

library:
  source-dirs: src
  exposed-modules:
    - BEncode 
    - Meta 
